### ISSUE TITLE
Implement stereo camera calibration routines

### ISSUE THREAD

**Issue by MattClarkson** [UCL/scikit-surgerycalibration#3]

**Comment by thompson318** [comment]
Hello Steven,

thanks for your questions, here are some answers. I've copied in Matt and Tom in case they disagree or want to add anything. At the bottom I've put some links to the wiki and slack channel. However we try and keep most of our discussions to the specific issue trackers on Weisslab or now github, that way we can hopefully go back and work out why we did stuff more easily. I've also attached the latest revision of the SNAPPY paper which is in the final stages of revision before IPCAI. 

The main thing with SNAPPY is to try and keep each library smallish and orthogonal, i.e. do one thing and minimise dependencies. It's really easy to manage lots of small libraries in Python, so we're trying to take advantage of it. Obviously sometimes libraries may grow too large and need dividing, or vice versa.

So surgeryimage should do image acquisition and some basic processing (feature detection, deinterlacing, undistortion, rectification etc).

surgerycalibration should do the calibration, with various implementations. So yes, I think the calibration bits should be moved out of surgeryimage and into surgerycalibration. Rather than making surgerycalibration a dependency of surgeryimage, the calibration bits of surgeryimage could just be depreciated with suitable error messages telling the developer where to find them now. Updating any dependent applications should then be straightforward.

I'm not sure if surgeryimage should be a dependency of surgerycalibration, to provide some image acquisition and basic processing.

There isn't really a set data flow for SNAPPY, as that would be application specific. SNAPPY just provides the libraries, which can then be assembled as the application developer wishes.

Adding package specific data types has pros and cons as you point out. We want the libraries to be as reusable as possible, so ideally should be avoided. One option is to put them into surgerycore, which all SNAPPY libraries can depend on. I have just added an abstract base class for scikitsurgery-trackers to it, so if you think it will be useful, you could do something similar for calibration data types.

thanks and regards,

Steve.

**Comment by thompson318** [comment]
I agree with this. I think that scikit-surgerycalibration should use image acquisition/processing and feature detectors implemented in scikit-surgeryimage. So yes, scikit-surgeryimage will be a dependency.

It will also be good if there are some calibration apps as part of the library so you can run it. As long as we're disciplined with keeping the algorithms and the user interface separate this shouldn't be a problem. So calibration algorithms go in sksurgerycalibration/algorithms or similar. User interfaces go in sksurgerycalibration/ui or similar. If in the future we think we need to split the library to manage dependencies, then that should be fairly straightforward.

regards,

Steve.

**Comment by tdowrick** [comment]
@MattClarkson 

Moving the conversation here from weisslab.

I have corrected the matrix multiplication ordering (I think - https://github.com/UCL/scikit-surgerycalibration/commit/e4f31f7a37c216192c3317f858af704b3fdb287c) and now everything seems quite sensible. Getting ~13 for the reprojection error and ~1.3 for reconstruction error using handeye calibration on the test data set.

For comparision, the reproj/recon error after stereo calibration are ~0.6 and ~1.6 respectively.

**Comment by tdowrick** [comment]
Right, I think we're getting there.

I've done some more general refactoring, and added in code so that MonoVideoCalibrationDriver can do a mono handeye calibration.

Mono reprojection/reconstruction errors coming out as 14.94/5.53 on the test data using the left channel as input.
